/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PropertyManagersRouteImport } from './routes/property-managers'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MailboxRouteImport } from './routes/mailbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as AgencyOfficesRouteImport } from './routes/agency-offices'
import { Route as AccountManagersRouteImport } from './routes/account-managers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencyOfficesOfficeIdRouteImport } from './routes/agency-offices_.$officeId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagersRoute = PropertyManagersRouteImport.update({
  id: '/property-managers',
  path: '/property-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxRoute = MailboxRouteImport.update({
  id: '/mailbox',
  path: '/mailbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyOfficesRoute = AgencyOfficesRouteImport.update({
  id: '/agency-offices',
  path: '/agency-offices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountManagersRoute = AccountManagersRouteImport.update({
  id: '/account-managers',
  path: '/account-managers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyOfficesOfficeIdRoute = AgencyOfficesOfficeIdRouteImport.update({
  id: '/agency-offices_/$officeId',
  path: '/agency-offices/$officeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-managers': typeof AccountManagersRoute
  '/agency-offices': typeof AgencyOfficesRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/mailbox': typeof MailboxRoute
  '/meetings': typeof MeetingsRoute
  '/pipeline': typeof PipelineRoute
  '/property-managers': typeof PropertyManagersRoute
  '/tasks': typeof TasksRoute
  '/agency-offices/$officeId': typeof AgencyOfficesOfficeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-managers': typeof AccountManagersRoute
  '/agency-offices': typeof AgencyOfficesRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/mailbox': typeof MailboxRoute
  '/meetings': typeof MeetingsRoute
  '/pipeline': typeof PipelineRoute
  '/property-managers': typeof PropertyManagersRoute
  '/tasks': typeof TasksRoute
  '/agency-offices/$officeId': typeof AgencyOfficesOfficeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-managers': typeof AccountManagersRoute
  '/agency-offices': typeof AgencyOfficesRoute
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/mailbox': typeof MailboxRoute
  '/meetings': typeof MeetingsRoute
  '/pipeline': typeof PipelineRoute
  '/property-managers': typeof PropertyManagersRoute
  '/tasks': typeof TasksRoute
  '/agency-offices_/$officeId': typeof AgencyOfficesOfficeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-managers'
    | '/agency-offices'
    | '/email-templates'
    | '/login'
    | '/mailbox'
    | '/meetings'
    | '/pipeline'
    | '/property-managers'
    | '/tasks'
    | '/agency-offices/$officeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-managers'
    | '/agency-offices'
    | '/email-templates'
    | '/login'
    | '/mailbox'
    | '/meetings'
    | '/pipeline'
    | '/property-managers'
    | '/tasks'
    | '/agency-offices/$officeId'
  id:
    | '__root__'
    | '/'
    | '/account-managers'
    | '/agency-offices'
    | '/email-templates'
    | '/login'
    | '/mailbox'
    | '/meetings'
    | '/pipeline'
    | '/property-managers'
    | '/tasks'
    | '/agency-offices_/$officeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountManagersRoute: typeof AccountManagersRoute
  AgencyOfficesRoute: typeof AgencyOfficesRoute
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  LoginRoute: typeof LoginRoute
  MailboxRoute: typeof MailboxRoute
  MeetingsRoute: typeof MeetingsRoute
  PipelineRoute: typeof PipelineRoute
  PropertyManagersRoute: typeof PropertyManagersRoute
  TasksRoute: typeof TasksRoute
  AgencyOfficesOfficeIdRoute: typeof AgencyOfficesOfficeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-managers': {
      id: '/property-managers'
      path: '/property-managers'
      fullPath: '/property-managers'
      preLoaderRoute: typeof PropertyManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailbox': {
      id: '/mailbox'
      path: '/mailbox'
      fullPath: '/mailbox'
      preLoaderRoute: typeof MailboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-offices': {
      id: '/agency-offices'
      path: '/agency-offices'
      fullPath: '/agency-offices'
      preLoaderRoute: typeof AgencyOfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-managers': {
      id: '/account-managers'
      path: '/account-managers'
      fullPath: '/account-managers'
      preLoaderRoute: typeof AccountManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-offices_/$officeId': {
      id: '/agency-offices_/$officeId'
      path: '/agency-offices/$officeId'
      fullPath: '/agency-offices/$officeId'
      preLoaderRoute: typeof AgencyOfficesOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountManagersRoute: AccountManagersRoute,
  AgencyOfficesRoute: AgencyOfficesRoute,
  EmailTemplatesRoute: EmailTemplatesRoute,
  LoginRoute: LoginRoute,
  MailboxRoute: MailboxRoute,
  MeetingsRoute: MeetingsRoute,
  PipelineRoute: PipelineRoute,
  PropertyManagersRoute: PropertyManagersRoute,
  TasksRoute: TasksRoute,
  AgencyOfficesOfficeIdRoute: AgencyOfficesOfficeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
